### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by LSGLSH** [forchannot/nonebot_plugin_rename#5]
```
04-20 23:29:14 [ERROR] nonebot | Failed to import "nonebot_plugin_rename"
Traceback (most recent call last):
  File "/home/bot/zhenxun_bot/bot.py", line 16, in <module>
    nonebot.load_plugins("my_plugins")
    │       └ <function load_plugins at 0x7f040e047670>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f040e03aee0>
           └ PluginManager(plugins=set(), search_path={'my_plugins'})
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
                  │    │           │         │       │    └ <property object at 0x7f040e036f40>
                  │    │           │         │       └ PluginManager(plugins=set(), search_path={'my_plugins'})
                  │    │           │         └ 'nonebot_plugin_rename'
                  │    │           └ 'nonebot_plugin_rename'
                  │    └ <function PluginManager.load_plugin at 0x7f040e03ae50>
                  └ PluginManager(plugins=set(), search_path={'my_plugins'})
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f040f5b7f70>
             └ <module 'importlib' from '/usr/lib/python3.9/importlib/__init__.py'>
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'my_plugins.nonebot_plugin_rename'
           │          └ <function _gcd_import at 0x7f040f6e3310>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'my_plugins.nonebot_plugin_rename' from '/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/__init__.py", line 3, in <module>
    from .main import *  # noqa
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/main.py", line 19, in <module>
    from .utils import *
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/utils/__init__.py", line 1, in <module>
    from .draw import generate_card_image
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/utils/draw.py", line 5, in <module>
    from .card_name import card_name_list as card_list
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/utils/card_name.py", line 3, in <module>
    from ..card import *
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/card/__init__.py", line 3, in <module>
    from .one_word import get_one_speak
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/card/one_word.py", line 7, in <module>
    async def get_one_speak() -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by LSGLSH** [comment]
可以的话能留个联系方式吗，GitHub的信息我不经常看

**Comment by forchannot** [comment]
哦，这个地方忘了改了，你py版本不够，我明天修改一下，改用typing

**Comment by forchannot** [comment]
已修复，还有问题可以提
