### ISSUE TITLE
查看群名片列表报错

### ISSUE THREAD

**Issue by LSGLSH** [forchannot/nonebot_plugin_rename#6]
```
04-21 11:36:38 [ERROR] nonebot | Running Matcher(type='message', module=my_plugins.nonebot_plugin_rename.main) failed.
Traceback (most recent call last):

  File "/home/bot/zhenxun_bot/bot.py", line 22, in <module>
    nonebot.run()
    │       └ <function run at 0x7f57bc8131f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f57bda913a0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7f57bb4a33a0>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x7f57bb4a3550>
    └ <uvicorn.server.Server object at 0x7f578b099670>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f57bb4a35e0>
           │       │   └ <uvicorn.server.Server object at 0x7f578b099670>
           │       └ <function run at 0x7f57bd6a54c0>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f578b084a40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f57bc6248b0>: <Task finished name='Task-121335' coro=<_command() done, defined at /root/.cache/pypo...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f57793f0880>
          │            │        │    │      └ {'_prefix': {'command': ('查看群名片列表',), 'raw_command': '查看群名片列表', 'command_arg': [], 'command_start': ''}}
          │            │        │    └ GroupMessageEvent(time=1682048197, self_id=3111654967, post_type='message', sub_type='normal', user_id=2368343278, message_ty...
          │            │        └ Bot(type='OneBot V11', self_id='3111654967')
          │            └ Matcher(type='message', module=my_plugins.nonebot_plugin_rename.main)
          └ <function _run_matcher at 0x7f57bc459280>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f57bc6248b0>: <Task finished name='Task-121335' coro=<_command() done, defined at /root/.cache/pypo...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f57793f0880>
          │       │   │    │      └ {'_prefix': {'command': ('查看群名片列表',), 'raw_command': '查看群名片列表', 'command_arg': [], 'command_start': ''}}
          │       │   │    └ GroupMessageEvent(time=1682048197, self_id=3111654967, post_type='message', sub_type='normal', user_id=2368343278, message_ty...
          │       │   └ Bot(type='OneBot V11', self_id='3111654967')
          │       └ <function Matcher.run at 0x7f57bc624550>
          └ Matcher(type='message', module=my_plugins.nonebot_plugin_rename.main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f57bc6248b0>: <Task finished name='Task-121335' coro=<_command() done, defined at /root/.cache/pypo...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f57793f0880>
          │    │          │    │      └ {'_prefix': {'command': ('查看群名片列表',), 'raw_command': '查看群名片列表', 'command_arg': [], 'command_start': ''}}
          │    │          │    └ GroupMessageEvent(time=1682048197, self_id=3111654967, post_type='message', sub_type='normal', user_id=2368343278, message_ty...
          │    │          └ Bot(type='OneBot V11', self_id='3111654967')
          │    └ <function Matcher.simple_run at 0x7f57bc6244c0>
          └ Matcher(type='message', module=my_plugins.nonebot_plugin_rename.main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
          └ Dependent(call=_)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'event': GroupMessageEvent(time=1682048197, self_id=3111654967, post_type='message', sub_type='normal', user_id=2368343278, ...
                 │    │             │         │    │    └ <function _ at 0x7f578bc0fca0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7f57bd998dc0>

  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/main.py", line 131, in _
    img = MessageSegment.image(generate_card_image())
          │              │     └ <function generate_card_image at 0x7f578bc0f310>
          │              └ <staticmethod object at 0x7f57bc4bc430>
          └ <class 'nonebot.adapters.onebot.v11.message.MessageSegment'>

  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_rename/utils/draw.py", line 17, in generate_card_image
    font = ImageFont.truetype(font_path, size=font_size)
           │         │        │               └ 20
           │         │        └ 'simhei.ttf'
           │         └ <function truetype at 0x7f57ab4d3430>
           └ <module 'PIL.ImageFont' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/PIL/Im...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/PIL/ImageFont.py", line 878, in truetype
    return freetype(font)
           │        └ 'simhei.ttf'
           └ <function truetype.<locals>.freetype at 0x7f5779d44f70>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/PIL/ImageFont.py", line 875, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           │            │     │     │      │         └ None
           │            │     │     │      └ ''
           │            │     │     └ 0
           │            │     └ 20
           │            └ 'simhei.ttf'
           └ <class 'PIL.ImageFont.FreeTypeFont'>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/PIL/ImageFont.py", line 226, in __init__
    self.font = core.getfont(
    │           │    └ <built-in function getfont>
    │           └ <module 'PIL._imagingft' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/PIL/_...
    └ <PIL.ImageFont.FreeTypeFont object at 0x7f5779410bb0>

OSError: cannot open resource
```

**Comment by forchannot** [comment]
已修复，等待action跑完更新试试

**Comment by forchannot** [comment]
由于现在第一次启动需要下载字体文件，可能启动较慢，如果服务器网速较差需要手动下载https://github.com/forchannot/nonebot_plugin_rename/tree/main/data/fonts中的字体文件到bot根目录/data/group_card/fonts/文件夹中
